USE CinemaDB;

INSERT INTO Movies VALUES
('Puss in Boots: The Last Wish', 102, 'PG', 'RqrXhwS33yc', 'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.'),
('Avatar: The Way of Water', 193, '12A', 'd9MyW72ELq0', 'Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Navi race to protect their planet.
'),
('Roald Dahls Matilda the Musical', 117, 'PG', 'lroAhsDr2vI', 'Matilda Wormwood is a little girl with big curiosity, a sharp mind and a vivid imagination — and the worst parents in the world. While her parents content themselves with trashy TV and dodgy money-making schemes, she loves to lose herself in the pages of her beloved books. On meeting an inspirational teacher, Matilda is encouraged and begins conjuring her own fantastical tales. Excited to attend Crunchem Hall, Matilda is surprised to find the school is an oppressive place led by the huge and villainous Miss Trunchbull. Filled with an overwhelming sense of justice, Matilda dares to take a stand for what is right and teach Trunchbull a lesson she wont forget.'),
('The Banshees of Inisherin', 113, '16', 'uRu3zLOJN2c', 'A pair of lifelong friends on a remote Irish island find themselves at an awkward time in their relationship when one of them no longer wants to be friends.'),
('I Wanna Dance With Somebody', 144, '12A', '9tfemzaMkoU', 'The joyous, emotional, heartbreaking celebration of the life and music of Whitney Houston, the greatest female R&B pop vocalist of all time. Tracking her journey from obscurity to musical superstardom'),
('Strange World', 102, 'PG', 'bKh2G73gCCs', 'A journey deep into an uncharted and treacherous land, where fantastical creatures await the legendary Clades—a family of explorers whose differences threaten to topple their latest, and by far most crucial, mission.'),
('The Fabelmans', 150, '12A', 'D1G2iLSzOe8', 'Growing up in post-World War II era Arizona, a young man named Sammy Fabelman discovers a shattering family secret and explores how the power of films can help him see the truth.'),
('Knock at the Cabin', 100, '15A', '0wiBHEACNHs', 'A young girl named Wen and her two fathers go on vacation to a remote cabin in a forest. They have fun swimming, and while her fathers are relaxing on the deck, Wen collects and and classifies insects. Suddenly, she notices a strange man walking through the woods towards the cabin. The man, named Leonard, introduces himself to Wen and is soon joined by three others. Wen and her fathers barricade themselves inside the house, but the four armed strangers break in. Leonard tells them they are there to prevent the apocalypse and to do that, they have to ask the family to make a terrible decision. With limited access to the outside world, the family must decide what they believe before all is lost.'),
('A Man Called Otto', 116, '12A', 'eFYUX9l-m5I', 'A grumpy widower whose only joy comes from criticizing and judging his exasperated neighbours meets his match when a lively young family moves in next door, leading to an unexpected friendship that will turn his world upside-down.'),
('Plane', 107, '15A', 'M25zXBIUVr0', 'In the white-knuckle action movie PLANE, pilot Brodie Torrance (Gerard Butler) saves his passengers from a lightning strike by making a risky landing on a war-torn island - only to find that surviving the landing was just the beginning. When most of the passengers are taken hostage by dangerous rebels, the only person Torrance can count on for help is Louis Gaspare (Mike Colter), an accused murderer who was being transported by the FBI. In order to rescue the passengers, Torrance will need Gaspares help, and will learn there’s more to Gaspare than meets the eye.'),
('Epic Tails', 95, 'PG', 'BH0rkCQjTfI', 'EPIC TAILS tells the story of super smart mouse Pattie and her feline friend Sam, as they embark upon an exciting adventure of paw-some proportions through Ancient Greece. With a little help from ageing hero Jason, the animals’ quest brings them face to face with some the most bizarre and dangerous creatures from Greek mythology, as they race to halt the threat posed to their city by Poseidon himself. A hilarious and inventive comedy adventure for the whole family, EPIC TAILS features the special guest voices of Rob Beckett, Giovanna Fletcher and Josh Widdicombe as the many Gods of Mount Olympus, including Zeus, Poseidon and Aphrodite.'),
('Magic Mike’s Last Dance', 112, '16', 'pBIGdw-BRxw', 'Join us for a special screening of Channing Tatum’s third and final outing as the titular male stripper as he goes to London to whip a hot new roster of talented dancers into shape. You’ll be served prosecco by our ‘Butlers in the Buff’, gorgeous men with ripped physiques who will be on hand for photos, to hand out complimentary popcorn, drinks, and souvenir posters. Expect fun, games, and lots of laughs. A great excuse to get everyone out for a much-needed night out.'),
('Pathaan (2D)', 166, '12A', 'vqu4z34wENw', 'Pathaan is an upcoming Hindi-language spy action-thriller film written and directed by Siddharth Anand and produced by Aditya Chopra under his banner Yash Raj Films.'),
('Titanic 3D', 186, '12A', 'I7c1etV7D7g', 'This spectacular epic re-creates the ill-fated maiden voyage of the White Star Lines $7.5 million R.M.S Titanic and the tragic sea disaster of April 15, 1912. Running over three hours and made with the combined contributions of two major studios (20th Century-Fox, Paramount) at a cost of more than $200 million, Titanic ranked as the most expensive film in Hollywood history at the time of its release, and became the most successful. Writer-director James Cameron employed state-of-the-art digital special effects for this production, realized on a monumental scale and spanning eight decades. Inspired by the 1985 discovery of the Titanic in the North Atlantic, the contemporary storyline involves American treasure-seeker Brock Lovett (Bill Paxton) retrieving artifacts from the submerged ship. Lovett looks for diamonds but finds a drawing of a young woman, nude except for a necklace. When 102-year-old Rose (Gloria Stuart) reveals shes the person in the portrait, she is summoned to the wreckage site to tell her story of the 56-carat diamond necklace and her experiences of 84 years earlier. The scene then shifts to 1912 Southampton where passengers boarding the Titanic include penniless Jack Dawson (Leonardo DiCaprio) and society girl Rose DeWitt Bukater (Kate Winslet), returning to Philadelphia with her wealthy fiance Cal Hockley (Billy Zane). After the April 10th launch, Rose develops a passionate interest in Jack, and Cals reaction is vengeful. At midpoint in the film, the Titanic slides against the iceberg and water rushes into the front compartments. Even engulfed, Cal continues to pursue Jack and Rose as the massive liner begins its descent. Cameron launched the project after seeing Robert Ballards 1987 National Geographic documentary on the wreckage. Blueprints of the real Titanic were followed during construction at Foxs custom-built Rosarito, Mexico studio, where a hydraulics system moved an immense model in a 17-million-gallon water tank. During three weeks aboard the Russian ship Academik Keldysh, underwater sequences were filmed with a 35mm camera in a titanium case mounted on the Russian submersible Mir 1. When the submersible neared the wreck, a video camera inside a remote-operated vehicle was sent into the Titanics 400-foot bow, bringing back footage of staterooms, furniture and chandeliers. On November 1, 1997, the film had its world premiere at the 10th Tokyo International Film Festival.')